### ISSUE TITLE
Solutions to Exercises

### ISSUE THREAD

**Issue by benperez** [goldfirere/glambda#4]
I remember attending this talk about a year ago, very cool! I'm currently trying to represent SQL expressions in Haskell and I have a hunch that GADT's could help. I'm trying to brush up on GADT's and I was wondering if the solutions to the exercises are available anywhere.

Thanks!

**Comment by goldfirere** [comment]
I've just pushed a new branch `solutions` that has what you're looking for. I'm glad this is helpful to you!

**Comment by benperez** [comment]
Thanks for the quick response!
