### ISSUE TITLE
Make Val injective

### ISSUE THREAD

**Issue by Icelandjack** [goldfirere/glambda#6]
`Val` from [`Exp.hs`](https://github.com/goldfirere/glambda/blob/master/src/Language/Glambda/Exp.hs) is a lovely thing to mark *injective* (and it looks very nice with instance sigs)

```haskell
{-# Language TypeFamilyDependencies #-}
{-# Language InstanceSigs #-}

class GlamVal t where
  type Val t = res | res -> t

  val :: Val t -> Exp '[] t

instance GlamVal Int where
  type Val Int = Int

  val :: Int -> Exp '[] Int
  val = IntE 

instance GlamVal Bool where
  type Val Bool = Bool

  val :: Bool -> Exp '[] Bool
  val = BoolE 

instance GlamVal (a -> b) where
  type Val (a -> b) = Exp '[a] b

  val :: Exp '[a] b -> Exp '[] (a -> b)
  val = Lam 
```

the `val` instances become even more basic, it also removes clutter throughout other modules.

**Comment by goldfirere** [comment]
Looking at this finally, I think I won't do this. The code in this package goes with a workshop I recorded years ago, and I don't want the code to diverge from the workshop. You're right that this is a valid simplification, however.
